services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3063:3000'
    command: sh -c "npm install && npm run dev"